version: "3.8"

services:
  backend:
    build:
      context: ./GAME/backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    ports:
      - "4999:4999"
    volumes:
      - ./GAME/backend:/app
      - ./GAME/backend/uploads:/app/uploads
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - transcendence_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/ft_front
      dockerfile: Dockerfile
    container_name: transcendence_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/ft_front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - transcendence_network
    depends_on:
      - backend
    restart: unless-stopped

  game:
    build:
      context: ./GAME
      dockerfile: Dockerfile
    container_name: transcendence_game
    ports:
      - "5174:5174"
    volumes:
      - ./GAME:/app
      - /app/node_modules
      - /app/backend
    environment:
      - NODE_ENV=development
    networks:
      - transcendence_network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  transcendence_network:
    driver: bridge
